server:
  port: 8080
#  servlet:
#    context-path: /api
logging:
  level:
    root: info
    com.kctud: debug
  file:
    name: logs/debug.log

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/book?useUnicode=true&characterEncoding=utf-8
    username: root
    password: NewPassword
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true