spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/spring_boot?useUnicode=true&characterEncoding=utf-8
    username: root
    password: NewPassword
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  profiles:
    active: dev
#logging:
#  config: classpath:logback-custom.xml
